-- Generated by nwg-displays on 2026-05-17 at 16:29:43. Do not edit manually.

hl.monitor({
    output = "",
    mode = "1920x1080@144.0",
    position = "0x216",
    scale = 1
})
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "0x216",
    scale = 1.25
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "1536x0",
    scale = 1.0
})
